- hosts: all
  vars:
    ansible_host_key_checking:  false
  become: true
  tasks:
  - name: copy war
    copy:
      src: /var/lib/jenkins/workspace/Claire-Deploy_with_sonarqube/target/bootcamp.war
      dest: /opt/docker/claire
  - name: Stop current container
    command: docker stop claire-devops-container
    ignore_errors: yes
  - name: remove stopped container
    command: docker rm claire-devops-container
    ignore_errors: yes
  - name: remover docker images # Clean up task
    command: docker rmi claire-devops-image:latest
    ignore_errors: yes # May not find image if first run
  - name: create docker image using war file
    command: docker build -t claire-devops-image:latest .
    args:
      chdir: /opt/docker/claire
  - name: run container
    command: docker run -d --name claire-devops-container -p 8081:8080 claire-devops-image:latest